{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  labels:
    app.kubernetes.io/name: runtime-secrets
    app.kubernetes.io/part-of: signalchord
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.global.existingSecret }}
    creationPolicy: Owner
  data:
    {{- range $item := .Values.externalSecret.data }}
    - secretKey: {{ $item.secretKey }}
      remoteRef:
        key: {{ $item.remoteRef.key | quote }}
        {{- with $item.remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
