{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name, $service := .Values.services }}
{{- if and $service.enabled (gt (int $service.replicas) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signalchord-{{ $name }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {app.kubernetes.io/name: {{ $name }}, app.kubernetes.io/part-of: signalchord}
{{- end }}
{{- end }}
{{- end }}
